apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "amundsen.name" . }}
    run: {{ .Chart.Name }}-{{ .Values.frontEnd.serviceName }}
    component: {{ .Values.frontEnd.serviceName }}
    chart: {{ template "amundsen.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "amundsen.name" . }}-{{ .Values.frontEnd.serviceName }}
spec:
  rules:
  - host: {{ .Values.frontEnd.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "amundsen.name" . }}-{{ .Values.frontEnd.serviceName }}
          servicePort: 5000